<!-- Basics of dataset -->

In [3]:
import pandas as pd
import numpy as np
from numpy.random import randn

<!--  -->

In [4]:
my_data = randn(4,3)        # this will create random data of 4 rows and 3 columns.
my_row = ["A","B","C","D"]
my_column = ["Mon","Wed", "Fri"]

In [5]:
my_df2 = pd.DataFrame(my_data, my_row, my_column)
print(my_df2)

        Mon       Wed       Fri
A -0.656044  0.605054 -0.094953
B -1.354712 -0.212640  1.335331
C -1.741748  1.414788 -1.422939
D -0.001668 -0.264304  0.289229

In [2]:
"""
this is how a dataframe is included in vs code.

"""

# Replace 'anish.csv' with your CSV file path
# we can write 'anish.csv' wherever we have used csv_file_path variable.
csv_file_path = 'anish.csv'

try:
    # Try reading the CSV file with default encoding
    df = pd.read_csv(csv_file_path)
except UnicodeDecodeError:
    # If there's an encoding error, try with a different encoding
    df = pd.read_csv(csv_file_path, encoding='latin1')

# Display the DataFrame
print(df)

      id                         name                            group  \
0      1              ENGLISH POINTER                    Pointing Dogs
1      2               ENGLISH SETTER                    Pointing Dogs
2      3           KERRY BLUE TERRIER                         Terriers
3      4                CAIRN TERRIER                         Terriers
4      5       ENGLISH COCKER SPANIEL                       Retrievers
..   ...                          ...                              ...
351  366               ESTONIAN HOUND  Scent hounds and related breeds
352  367  MINIATURE AMERICAN SHEPHERD         Sheepdogs and Cattledogs
353  368         TRANSMONTANO MASTIFF           Pinscher and Schnauzer
354  369          CONTINENTAL BULLDOG           Pinscher and Schnauzer
355  370            VALENCIAN TERRIER                         Terriers

                                    section provisional  \
0    British and Irish Pointers and Setters         NaN
1    British and Irish Pointers and Setters         NaN
2           Large and medium sized Terriers         NaN
3                      Small sized Terriers         NaN
4                             Flushing Dogs         NaN
..                                      ...         ...
351                            Scent hounds    9/4/2019
352                               Sheepdogs    9/4/2019
353                          Molossian type   2/26/2020
354                          Molossian type   3/30/2022
355         Large and medium sized Terriers   6/21/2022

                      country  \
0               GREAT BRITAIN
1               GREAT BRITAIN
2                     IRELAND
3               GREAT BRITAIN
4               GREAT BRITAIN
..                        ...
351                   ESTONIA
352  UNITED STATES OF AMERICA
353                  PORTUGAL
354               SWITZERLAND
355                     SPAIN

                                                   url  \
0    https://www.fci.be/en/nomenclature/ENGLISH-POI...
1    https://www.fci.be/en/nomenclature/ENGLISH-SET...
2    https://www.fci.be/en/nomenclature/KERRY-BLUE-...
3    https://www.fci.be/en/nomenclature/CAIRN-TERRI...
4    https://www.fci.be/en/nomenclature/ENGLISH-COC...
..                                                 ...
351  https://www.fci.be/en/nomenclature/ESTONIAN-HO...
352  https://www.fci.be/en/nomenclature/MINIATURE-A...
353  https://www.fci.be/en/nomenclature/TRANSMONTAN...
354  https://www.fci.be/en/nomenclature/CONTINENTAL...
355  https://www.fci.be/en/nomenclature/VALENCIAN-T...

                                                 image  \
0    https://www.fci.be/Nomenclature/Illustrations/...
1    https://www.fci.be/Nomenclature/Illustrations/...
2                                                  NaN
3    https://www.fci.be/Nomenclature/Illustrations/...
4    https://www.fci.be/Nomenclature/Illustrations/...
..                                                 ...
351  https://www.fci.be/Nomenclature/Illustrations/...
352                                                NaN
353  https://www.fci.be/Nomenclature/Illustrations/...
354  https://www.fci.be/Nomenclature/Illustrations/...
355  https://www.fci.be/Nomenclature/Illustrations/...

                                                   pdf
0    https://www.fci.be/Nomenclature/Standards/001g...
1    https://www.fci.be/Nomenclature/Standards/002g...
2    https://www.fci.be/Nomenclature/Standards/003g...
3    https://www.fci.be/Nomenclature/Standards/004g...
4    https://www.fci.be/Nomenclature/Standards/005g...
..                                                 ...
351  https://www.fci.be/Nomenclature/Standards/366g...
352  https://www.fci.be/Nomenclature/Standards/367g...
353  https://www.fci.be/Nomenclature/Standards/368g...
354  https://www.fci.be/Nomenclature/Standards/369g...
355  https://www.fci.be/Nomenclature/Standards/370g...

[356 rows x 9 columns]

In [40]:
# Pull out a row
df.loc[0]       # this will print us our first row.

id                                                             1
name                                             ENGLISH POINTER
group                                              Pointing Dogs
section                   British and Irish Pointers and Setters
provisional                                                  NaN
country                                            GREAT BRITAIN
url            https://www.fci.be/en/nomenclature/ENGLISH-POI...
image          https://www.fci.be/Nomenclature/Illustrations/...
pdf            https://www.fci.be/Nomenclature/Standards/001g...
Name: 0, dtype: object

In [45]:
df.loc[[0,1,2,3]]

,id,name,group,section,provisional,country,url,image,pdf
0,1,ENGLISH POINTER,Pointing Dogs,British and Irish Pointers and Setters,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/ENGLISH-POI...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/001g...
1,2,ENGLISH SETTER,Pointing Dogs,British and Irish Pointers and Setters,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/ENGLISH-SET...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/002g...
2,3,KERRY BLUE TERRIER,Terriers,Large and medium sized Terriers,NaN,IRELAND,https://www.fci.be/en/nomenclature/KERRY-BLUE-...,NaN,https://www.fci.be/Nomenclature/Standards/003g...
3,4,CAIRN TERRIER,Terriers,Small sized Terriers,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/CAIRN-TERRI...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/004g...

In [46]:
# function to get/print first 5 rows of the dataset.
df.head()

,id,name,group,section,provisional,country,url,image,pdf
0,1,ENGLISH POINTER,Pointing Dogs,British and Irish Pointers and Setters,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/ENGLISH-POI...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/001g...
1,2,ENGLISH SETTER,Pointing Dogs,British and Irish Pointers and Setters,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/ENGLISH-SET...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/002g...
2,3,KERRY BLUE TERRIER,Terriers,Large and medium sized Terriers,NaN,IRELAND,https://www.fci.be/en/nomenclature/KERRY-BLUE-...,NaN,https://www.fci.be/Nomenclature/Standards/003g...
3,4,CAIRN TERRIER,Terriers,Small sized Terriers,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/CAIRN-TERRI...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/004g...
4,5,ENGLISH COCKER SPANIEL,Retrievers,Flushing Dogs,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/ENGLISH-COC...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/005g...

In [47]:
# fun to get wanted number of rows. dataset_name.head(no. of rows)
# getting first 10 rows of the dataset.
df.head(10)

,id,name,group,section,provisional,country,url,image,pdf
0,1,ENGLISH POINTER,Pointing Dogs,British and Irish Pointers and Setters,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/ENGLISH-POI...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/001g...
1,2,ENGLISH SETTER,Pointing Dogs,British and Irish Pointers and Setters,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/ENGLISH-SET...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/002g...
2,3,KERRY BLUE TERRIER,Terriers,Large and medium sized Terriers,NaN,IRELAND,https://www.fci.be/en/nomenclature/KERRY-BLUE-...,NaN,https://www.fci.be/Nomenclature/Standards/003g...
3,4,CAIRN TERRIER,Terriers,Small sized Terriers,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/CAIRN-TERRI...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/004g...
4,5,ENGLISH COCKER SPANIEL,Retrievers,Flushing Dogs,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/ENGLISH-COC...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/005g...
5,6,GORDON SETTER,Pointing Dogs,British and Irish Pointers and Setters,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/GORDON-SETT...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/006g...
6,7,AIREDALE TERRIER,Terriers,Large and medium sized Terriers,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/AIREDALE-TE...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/007g...
7,8,AUSTRALIAN TERRIER,Terriers,Small sized Terriers,NaN,AUSTRALIA,https://www.fci.be/en/nomenclature/AUSTRALIAN-...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/008g...
8,9,BEDLINGTON TERRIER,Terriers,Large and medium sized Terriers,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/BEDLINGTON-...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/009g...
9,10,BORDER TERRIER,Terriers,Large and medium sized Terriers,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/BORDER-TERR...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/010g...

In [48]:
# grab last 5 rows of the dataset.
df.tail()

,id,name,group,section,provisional,country,url,image,pdf
351,366,ESTONIAN HOUND,Scent hounds and related breeds,Scent hounds,9/4/2019,ESTONIA,https://www.fci.be/en/nomenclature/ESTONIAN-HO...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/366g...
352,367,MINIATURE AMERICAN SHEPHERD,Sheepdogs and Cattledogs,Sheepdogs,9/4/2019,UNITED STATES OF AMERICA,https://www.fci.be/en/nomenclature/MINIATURE-A...,NaN,https://www.fci.be/Nomenclature/Standards/367g...
353,368,TRANSMONTANO MASTIFF,Pinscher and Schnauzer,Molossian type,2/26/2020,PORTUGAL,https://www.fci.be/en/nomenclature/TRANSMONTAN...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/368g...
354,369,CONTINENTAL BULLDOG,Pinscher and Schnauzer,Molossian type,3/30/2022,SWITZERLAND,https://www.fci.be/en/nomenclature/CONTINENTAL...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/369g...
355,370,VALENCIAN TERRIER,Terriers,Large and medium sized Terriers,6/21/2022,SPAIN,https://www.fci.be/en/nomenclature/VALENCIAN-T...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/370g...

In [49]:
# last certain number of last rows, 10 in this case.
df.tail(10)

,id,name,group,section,provisional,country,url,image,pdf
346,361,SEGUGIO MAREMMANO,Scent hounds and related breeds,Scent hounds,3/1/2018,ITALY,https://www.fci.be/en/nomenclature/SEGUGIO-MAR...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/361g...
347,362,KINTAMANI-BALI DOG,Spitz and primitive types,Asian Spitz and related breeds,2/20/2019,INDONESIA,https://www.fci.be/en/nomenclature/KINTAMANI-B...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/362g...
348,363,PRAGUE RATTER,Companion and Toy Dogs,Continental Toy Spaniel and others,4/29/2019,CZECH REPUBLIC,https://www.fci.be/en/nomenclature/PRAGUE-RATT...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/363g...
349,364,BOHEMIAN SHEPHERD DOG,Sheepdogs and Cattledogs,Sheepdogs,4/29/2019,CZECH REPUBLIC,https://www.fci.be/en/nomenclature/BOHEMIAN-SH...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/364g...
350,365,YAKUTIAN LAIKA,Spitz and primitive types,Nordic Sledge Dogs,9/4/2019,RUSSIAN FEDERATION,https://www.fci.be/en/nomenclature/YAKUTIAN-LA...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/365g...
351,366,ESTONIAN HOUND,Scent hounds and related breeds,Scent hounds,9/4/2019,ESTONIA,https://www.fci.be/en/nomenclature/ESTONIAN-HO...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/366g...
352,367,MINIATURE AMERICAN SHEPHERD,Sheepdogs and Cattledogs,Sheepdogs,9/4/2019,UNITED STATES OF AMERICA,https://www.fci.be/en/nomenclature/MINIATURE-A...,NaN,https://www.fci.be/Nomenclature/Standards/367g...
353,368,TRANSMONTANO MASTIFF,Pinscher and Schnauzer,Molossian type,2/26/2020,PORTUGAL,https://www.fci.be/en/nomenclature/TRANSMONTAN...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/368g...
354,369,CONTINENTAL BULLDOG,Pinscher and Schnauzer,Molossian type,3/30/2022,SWITZERLAND,https://www.fci.be/en/nomenclature/CONTINENTAL...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/369g...
355,370,VALENCIAN TERRIER,Terriers,Large and medium sized Terriers,6/21/2022,SPAIN,https://www.fci.be/en/nomenclature/VALENCIAN-T...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/370g...

In [50]:
# get info about dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356 entries, 0 to 355
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           356 non-null    int64
 1   name         356 non-null    object
 2   group        356 non-null    object
 3   section      355 non-null    object
 4   provisional  12 non-null     object
 5   country      356 non-null    object
 6   url          356 non-null    object
 7   image        264 non-null    object
 8   pdf          355 non-null    object
dtypes: int64(1), object(8)
memory usage: 25.2+ KB

In [53]:
# get the shape of dataset as (row,column)
df.shape

(356, 9)

In [54]:
# dimension is 2D in this case.
df.ndim

2

In [56]:
# returns the datatype of all columns in the dataset.
df.dtypes

id              int64
name           object
group          object
section        object
provisional    object
country        object
url            object
image          object
pdf            object
dtype: object

In [57]:
# get some statistic about the data
# it's saying that well id column have numbers with it so I'll do stuff with it.
df.describe()

               id
count  356.000000
mean   187.910112
std    106.667908
min      1.000000
25%     96.750000
50%    188.500000
75%    281.250000
max    370.000000

In [58]:
# describe a specific column
df['country'].describe()

count               356
unique               64
top       GREAT BRITAIN
freq                 57
Name: country, dtype: object

In [59]:
# describe a specific column
df['name'].describe()

count                 356
unique                356
top       ENGLISH POINTER
freq                    1
Name: name, dtype: object

In [60]:
# getting individual column
# df.country        this will do same as the following. 
df['country']

0                 GREAT BRITAIN
1                 GREAT BRITAIN
2                       IRELAND
3                 GREAT BRITAIN
4                 GREAT BRITAIN
                 ...
351                     ESTONIA
352    UNITED STATES OF AMERICA
353                    PORTUGAL
354                 SWITZERLAND
355                       SPAIN
Name: country, Length: 356, dtype: object

In [63]:
# rows access karna from (start to end) excluding the end .
df.iloc[0 : 4]

,id,name,group,section,provisional,country,url,image,pdf
0,1,ENGLISH POINTER,Pointing Dogs,British and Irish Pointers and Setters,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/ENGLISH-POI...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/001g...
1,2,ENGLISH SETTER,Pointing Dogs,British and Irish Pointers and Setters,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/ENGLISH-SET...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/002g...
2,3,KERRY BLUE TERRIER,Terriers,Large and medium sized Terriers,NaN,IRELAND,https://www.fci.be/en/nomenclature/KERRY-BLUE-...,NaN,https://www.fci.be/Nomenclature/Standards/003g...
3,4,CAIRN TERRIER,Terriers,Small sized Terriers,NaN,GREAT BRITAIN,https://www.fci.be/en/nomenclature/CAIRN-TERRI...,https://www.fci.be/Nomenclature/Illustrations/...,https://www.fci.be/Nomenclature/Standards/004g...

In [65]:
# accessing a specific column by its index
# here we are accessing the 2nd column by its index.
df.iloc[ :, 1]

0                  ENGLISH POINTER
1                   ENGLISH SETTER
2               KERRY BLUE TERRIER
3                    CAIRN TERRIER
4           ENGLISH COCKER SPANIEL
                  ...
351                 ESTONIAN HOUND
352    MINIATURE AMERICAN SHEPHERD
353           TRANSMONTANO MASTIFF
354            CONTINENTAL BULLDOG
355              VALENCIAN TERRIER
Name: name, Length: 356, dtype: object